### ISSUE TITLE
Database needs to be created with utf8 as the default character set

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django-vagrant-install#11]
Currently it is created with latin1, which won't work with all of our production data and will make testing unicode issues problematic.

**Comment by handrews** [comment]
Hmm... looking at puppet/profiles/database_profile/manifests/params.pp it looks like all character set related things are properly set to utf8.  @grosenbaum can you think of any reason why that wouldn't be carrying through to the database that gets created?

**Comment by grosenbaum** [comment]
character-set are are  properly set to utf8 for both server and client. I can't explain why the `gcd` database is created with a latin1 character set. I'll do my best to figure it out (more information in the mysql module: grant.pp, ...).

**Comment by handrews** [comment]
I didn't see anything in grant.pp to help, but I looked at /root/puppet-mysql/mysqlgrant-gcd-localhost-gcd.sql and these are the contents:

# This file is managed by Puppet. DO NOT EDIT.
CREATE DATABASE IF NOT EXISTS `gcd`;
GRANT ALL ON `gcd`.* TO 'gcd'@'localhost' IDENTIFIED BY 'gcd';
FLUSH PRIVILEGES ;

That CREATE DATABASE statement should be

CREATE DATABASE IF NOT EXISTS `gcd` DEFAULT CHARACTER SET utf8;

so that's the immediate reason why it's getting created with latin1 (I've never seen a setting that would get it to set utf8 without including it in the create statement, although admittedly I've never really looked).

**Comment by handrews** [comment]
I believe I fixed this in commit efa92ce7fd84813093ed1843aea890e33a38f045
