### ISSUE TITLE
Our versions of pip and distribute aren't correct

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django-vagrant-install#12]
At least some packages in our requirements.txt will not install with the versions of pip (for mock) and distrbute (I forget which package has this problem) that we have in the dev environment.

To complicate this, some packages won't install with the most recent version of pip.  I am not sure what the correct versions are to get this all to work (why is the state of python package management perpetually horrific and ununified?)

MySQL-python 1.2.4c will not install with the current version of pip, but MySQL-python 1.2.5 (the current version) will, and we should probably be using that anyway so I will fix that in the requirements.txt.

However, diff-patch-match-20121119 (which is the most recent version) also will not install under current pip, so I do not know what to do about that.

**Comment by jochengcd** [comment]
In what way fails ? With these changes pip 8.1.2 gets all installed, distribute is not needed any more with current version of stdnum (which should be safe to upgrade), while I needed to update pyICU to get it to compile
 BeautifulSoup==3.2.1
 Django<1.8
-MySQL-python==1.2.4c1
+MySQL-python==1.2.5
 Pillow<2.0
-PyICU==1.4
+PyICU==1.9.3
 PyYAML==3.10
 Pygments==1.5
 pytz==2016.6.1
 argparse==1.2.1
 diff-match-patch==20121119
-distribute==0.6.32
+#distribute==0.7.3
 django-appconf==1.0.2
 django-bootstrap3==6.2.2
 django-compressor==1.4
@@ -27,7 +27,7 @@ pyelasticsearch==0.6.1
 python-dateutil==2.2
 python-graph-core==1.8.2
 python-memcached==1.48
-python-stdnum==0.7
+python-stdnum==1.3
 python-vote-core==20120423.0
 redis==2.10.1
 requests==2.2.1

**Comment by handrews** [comment]
Looks like that fixes it- after the third error (which I guess must have been the stdnum thing?) I gave up and filed it so I could work on something else in the meantime (I have an envirnoment that was partially installed under old versions and partially installed under new that works well enough).

So we still do need to update the version of pip, though.  The one that comes in the vagrant environment (pip 1.0) will not properly install mock, which we need for the unit tests (which is what I'm working on right now on a new branch while waiting to get the django17 branch merged and deployed).

**Comment by jochengcd** [comment]
I don't know anything (or much) about the vagrant install...

**Comment by handrews** [comment]
No worries, @grosenbaum or I can fix it.  But that's why I filed this on gcd-django-vagrant-install instead of gcd-django.

**Comment by handrews** [comment]
With updated libraries in our requirements.txt, we now no longer need distribute, but do need the latest pip.

**Comment by handrews** [comment]
Posted for review: http://reviews.comics.org/r/1733/
