### ISSUE TITLE
Cover thumbnail doesn't match uploaded cover

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django-vagrant-install#13]
http://www.comics.org/changeset/2801444/compare/
The thumbnail is the same as before, but the uploaded full size cover is new. 

I could just have him upload the cover again, but figured I should mention it just in case it's indicative of something.

**Comment by bookcats** [comment]
I think I put this in the wrong place. I couldn't figure out how to get here... The wiki still links to bugzilla on the front page not github.

**Comment by handrews** [comment]
I think you wanted to file this at https://github.com/GrandComicsDatabase/gcd-django/issues
I've updated the link on the wiki front page, thanks for pointing that out.
