### ISSUE TITLE
virtualenv confused about /usr/local/virtualenv vs /usr/virtualenv

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django-vagrant-install#4]
The python virtual environment in the VM is at `/usr/local/virtualenv`, but some things seem to think that it is at `/usr/virtualenv`:

    [vagrant@gcd-django-box /vagrant (master)]$ source /usr/local/virtualenv/bin/activate
    (virtualenv)[vagrant@gcd-django-box /vagrant (master)]$ which pip
    /usr/local/virtualenv/bin/pip
    (virtualenv)[vagrant@gcd-django-box /vagrant (master)]$ pip --help
    /usr/local/virtualenv/local/lib/python2.7/site-packages/pip/pep425tags.py:66: RuntimeWarning: invalid Python installation: unable to open /usr/virtualenv/lib/python2.7/config/Makefile (No such file or directory)
      warnings.warn("{0}".format(e), RuntimeWarning)

    [regular pip --help output follows]

No `/usr/virtualenv` directory exists.

According to @grosenbaum 
"""
Seems to be a problem with python package of Ubuntu (see https://github.com/pypa/pip/issues/1074)

Simple solution, I suggest to move virtualenv from /usr/local to /opt.
"""

**Comment by grosenbaum** [comment]
Fix in #5
