### ISSUE TITLE
Run virtualenv upon vagrant ssh

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django-vagrant-install#6]
It would be ideal for the default configuration to source /opt/virtualenv/bin/activate on login.  I can't figure out the right incantation in my custom zsh file to do this- what I do in bash apparently does not work.

**Comment by grosenbaum** [comment]
@handrews I'll check this

**Comment by grosenbaum** [comment]
@handrews Done :)

**Comment by handrews** [comment]
I just re-tested this with a new checkout, immediately running provision without tweaking anything first, checking /home/vagrant/.zshrc but not touching anything, and then running make install, again without changing anything first.

At the end of all this (and when the .zshrc was checked in the middle) there is nothing anywhere that sources the virtualenv.  Which is weird because the change that you made to do this is still there.  I can't follow what's going on well enough to debug it- forgot most of the puppet stuff I learned last time I looked at this and need to read up on it again.

I also manually added 
source /opt/virtualenv/bin/activate
at the end of /home/vagrant/.zshrc, and verified that if I log out and vagrant ssh back in, the virtualenv is in fact loaded.  So that solution will work, if the line gets into the file.

**Comment by gcd-github** [comment]
The problem here is *.zshrc*. This time, the puppet catalog is build in a 
different order then before (don't know why). Then, this conf tries to add 
a line in an inexistant file:

  file_line { "/home/${real_default_user}/.zshrc":
    path    => "/home/${real_default_user}/.zshrc",
    line    => 'source /opt/virtualenv/bin/activate'
  }

To fix that until I commit and push my fix, just add:

  file_line { "/home/${real_default_user}/.zshrc":
    path    => "/home/${real_default_user}/.zshrc",
    line    => 'source /opt/virtualenv/bin/activate',
    require => Ohmyzsh::Install[$real_default_user],
  }

Gilles

**Comment by handrews** [comment]
Apparently I applied Gilles's fix in commit fc499fda
