### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by davgar** [GrandComicsDatabase/gcd-django-vagrant-install#7]
Hello,

I just re-downloaded the install in a different folder and here is what I am getting.. I am using El Capitan if it maters... 

Bringing machine 'local' up with 'virtualbox' provider...
==> local: Checking if box 'hashicorp/precise32' is up to date...
==> local: Clearing any previously set forwarded ports...
==> local: Clearing any previously set network interfaces...
==> local: Preparing network interfaces based on configuration...
    local: Adapter 1: nat
    local: Adapter 2: hostonly
==> local: Forwarding ports...
    local: 8000 => 8000 (adapter 1)
    local: 22 => 2222 (adapter 1)
==> local: Running 'pre-boot' VM customizations...
==> local: Booting VM...
==> local: Waiting for machine to boot. This may take a few minutes...
    local: SSH address: 127.0.0.1:2222
    local: SSH username: vagrant
    local: SSH auth method: private key
    local: Warning: Connection timeout. Retrying...
==> local: Machine booted and ready!
==> local: Checking for guest additions in VM...
    local: The guest additions on this VM do not match the installed version of
    local: VirtualBox! In most cases this is fine, but in rare cases it can
    local: prevent things such as shared folders from working properly. If you see
    local: shared folder errors, please make sure the guest additions within the
    local: virtual machine match the version of VirtualBox you have installed on
    local: your host and reload your VM.
    local: 
    local: Guest Additions Version: 4.2.0
    local: VirtualBox Version: 4.3
==> local: Setting hostname...
==> local: Configuring and enabling network interfaces...
==> local: Mounting shared folders...
    local: /vagrant => /Users/dg/Documents/gcd-django-vagrant-install
==> local: Running provisioner: shell...
    local: Running: inline script
==> local: stdin: is not a tty
==> local: Puppet is already installed
==> local: false
==> local: Installing RubyGems
==> local: Successfully installed rubygems-update-2.4.8
==> local: Successfully installed deep_merge-1.0.1
==> local: 2 gems installed
==> local: /usr/lib/ruby/1.8/rdoc/rdoc.rb:280: warning: conflicting chdir during another chdir block
==> local: /usr/lib/ruby/1.8/rdoc/rdoc.rb:287: warning: conflicting chdir during another chdir block
==> local: Gems installed!
==> local: Git is already installed.
==> local: Git submodules are already installed
==> local: Running provisioner: shell...
    local: Running: inline script
==> local: stdin: is not a tty
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: WARN: Sat Oct 31 02:04:02 +0000 2015: Ignoring configured merge_behavior
==> local: WARN: Sat Oct 31 02:04:02 +0000 2015: Must have 'deep_merge' gem installed.
==> local: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class ntp at /vagrant/puppet/profiles/base_profile/manifests/init.pp:75 on node gcd-django-box
==> local: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class ntp at /vagrant/puppet/profiles/base_profile/manifests/init.pp:75 on node gcd-django-box
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

David

**Comment by grosenbaum** [comment]
Hi @davgar 
Thx for submitting this issue.
Seems that you have missing git submodules.
Could you please write exactly how do you setup your env. ?
I'm using El Capitan too, I'll try to reproduce your pb.
Gilles

**Comment by davgar** [comment]
I can keep going I think this is the problem. 

mkdir troubleshooting
cd troubleshooting
git clone --recurse-submodules https://github.com/GrandComicsDatabase/gcd-django-vagrant-install

all
Cloning into 'gcd-django-vagrant-install'...
remote: Counting objects: 457, done.
remote: Total 457 (delta 0), reused 0 (delta 0), pack-reused 457
Receiving objects: 100% (457/457), 69.01 KiB | 0 bytes/s, done.
Resolving deltas: 100% (191/191), done.
Checking connectivity... done.
Submodule 'puppet/modules/apt' (git://github.com/puppetlabs/puppetlabs-apt.git) registered for path 'puppet/modules/apt'
Submodule 'puppet/modules/elasticsearch' (git://github.com/elasticsearch/puppet-elasticsearch.git) registered for path 'puppet/modules/elasticsearch'
Submodule 'puppet/modules/git' (git://github.com/example42/puppet-git.git) registered for path 'puppet/modules/git'
Submodule 'puppet/modules/java' (git://github.com/puppetlabs/puppetlabs-java.git) registered for path 'puppet/modules/java'
Submodule 'puppet/modules/locales' (git://github.com/saz/puppet-locales.git) registered for path 'puppet/modules/locales'
Submodule 'puppet/modules/mysql' (git://github.com/example42/puppet-mysql.git) registered for path 'puppet/modules/mysql'
Submodule 'puppet/modules/ohmyzsh' (git://github.com/acme/puppet-acme-oh-my-zsh.git) registered for path 'puppet/modules/ohmyzsh'
Submodule 'puppet/modules/puppi' (git://github.com/example42/puppi.git) registered for path 'puppet/modules/puppi'
Submodule 'puppet/modules/python' (git://github.com/stankevich/puppet-python.git) registered for path 'puppet/modules/python'
Submodule 'puppet/modules/stdlib' (git://github.com/puppetlabs/puppetlabs-stdlib.git) registered for path 'puppet/modules/stdlib'
Cloning into 'puppet/modules/apt'...
remote: Counting objects: 4230, done.
remote: Total 4230 (delta 0), reused 0 (delta 0), pack-reused 4230
Receiving objects: 100% (4230/4230), 939.83 KiB | 1.27 MiB/s, done.
Resolving deltas: 100% (2367/2367), done.
Checking connectivity... done.
Submodule path 'puppet/modules/apt': checked out 'e671b38635b7d0ec8baff171cc8d389731ffa238'
Cloning into 'puppet/modules/elasticsearch'...
remote: Counting objects: 3447, done.
remote: Total 3447 (delta 0), reused 0 (delta 0), pack-reused 3447
Receiving objects: 100% (3447/3447), 722.48 KiB | 682.00 KiB/s, done.
Resolving deltas: 100% (2185/2185), done.
Checking connectivity... done.
Submodule path 'puppet/modules/elasticsearch': checked out '4103069232e4b8e5399bc8bbac7b85219cccbbe4'
Cloning into 'puppet/modules/git'...
remote: Counting objects: 184, done.
remote: Total 184 (delta 0), reused 0 (delta 0), pack-reused 184
Receiving objects: 100% (184/184), 30.99 KiB | 0 bytes/s, done.
Resolving deltas: 100% (76/76), done.
Checking connectivity... done.
Submodule path 'puppet/modules/git': checked out 'c038ad17a5ac460df666262045c0ceba3faf6706'
Cloning into 'puppet/modules/java'...
remote: Counting objects: 949, done.
remote: Total 949 (delta 0), reused 0 (delta 0), pack-reused 949
Receiving objects: 100% (949/949), 166.60 KiB | 0 bytes/s, done.
Resolving deltas: 100% (403/403), done.
Checking connectivity... done.
Submodule path 'puppet/modules/java': checked out '1b9bb75de830f0ddf6c920bf05e3ea3859b767db'
Cloning into 'puppet/modules/locales'...
remote: Counting objects: 195, done.
remote: Total 195 (delta 0), reused 0 (delta 0), pack-reused 195
Receiving objects: 100% (195/195), 27.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (70/70), done.
Checking connectivity... done.
Submodule path 'puppet/modules/locales': checked out '0c17394b2257bde5597c86194fa7a022d69385a2'
Cloning into 'puppet/modules/mysql'...
remote: Counting objects: 542, done.
remote: Total 542 (delta 0), reused 0 (delta 0), pack-reused 542
Receiving objects: 100% (542/542), 102.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (292/292), done.
Checking connectivity... done.
Submodule path 'puppet/modules/mysql': checked out '6f9858e4b2461ce42eb05cd1242cdbfe971206ae'
Cloning into 'puppet/modules/ohmyzsh'...
remote: Counting objects: 107, done.
remote: Total 107 (delta 0), reused 0 (delta 0), pack-reused 107
Receiving objects: 100% (107/107), 21.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (42/42), done.
Checking connectivity... done.
Submodule path 'puppet/modules/ohmyzsh': checked out 'f61cc46823f0aa2cd012668a6182e83f4557418d'
Cloning into 'puppet/modules/puppi'...
remote: Counting objects: 2124, done.
remote: Total 2124 (delta 0), reused 0 (delta 0), pack-reused 2124
Receiving objects: 100% (2124/2124), 477.26 KiB | 616.00 KiB/s, done.
Resolving deltas: 100% (1139/1139), done.
Checking connectivity... done.
Submodule path 'puppet/modules/puppi': checked out 'faed9e56cf541b12bcf462006053bc762ed241c6'
Cloning into 'puppet/modules/python'...
remote: Counting objects: 2057, done.
remote: Total 2057 (delta 0), reused 0 (delta 0), pack-reused 2057
Receiving objects: 100% (2057/2057), 351.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1137/1137), done.
Checking connectivity... done.
fatal: reference is not a tree: cf744a4120990d798597ee11b61c471976fa847a
Cloning into 'puppet/modules/stdlib'...
remote: Counting objects: 7549, done.
remote: Total 7549 (delta 0), reused 0 (delta 0), pack-reused 7549
Receiving objects: 100% (7549/7549), 1.57 MiB | 933.00 KiB/s, done.
Resolving deltas: 100% (3360/3360), done.
Checking connectivity... done.
Submodule path 'puppet/modules/stdlib': checked out '14a02ea21e14111071a921e82cdf3cd1f518c7f3'
Unable to checkout 'cf744a4120990d798597ee11b61c471976fa847a' in submodule path 'puppet/modules/python'

**Comment by grosenbaum** [comment]
Thx @davgar for the log. I reproduced your pb.

@handrews 
I fix this bug but I can't push it to the RB because of an empty diff. 
I've just updated git submodules references. 
The diff:
```
    Fix git submodules causing problem in install #7
---
 puppet/modules/ntp      |    1 +
 puppet/modules/python   |    2 +-
 puppet/modules/timezone |    1 +
 3 files changed, 3 insertions(+), 1 deletion(-)

diff --git a/puppet/modules/ntp b/puppet/modules/ntp
new file mode 160000
index 0000000..9d548a2
--- /dev/null
+++ b/puppet/modules/ntp
@@ -0,0 +1 @@
+Subproject commit 9d548a20ba46feb049471140f640daa16d967828
diff --git a/puppet/modules/python b/puppet/modules/python
index cf744a4..e7389f6 160000
--- a/puppet/modules/python
+++ b/puppet/modules/python
@@ -1 +1 @@
-Subproject commit cf744a4120990d798597ee11b61c471976fa847a
+Subproject commit e7389f6e270796372b93b178fd5295abefbdc17a
diff --git a/puppet/modules/timezone b/puppet/modules/timezone
new file mode 160000
index 0000000..7349189
--- /dev/null
+++ b/puppet/modules/timezone
@@ -0,0 +1 @@
+Subproject commit 734918982a512f51a3f1855396d2d7da3f37f53c
```

Can I push without a review ?
Thx
Gilles

**Comment by handrews** [comment]
@grosenbaum :  Ship it!

**Comment by grosenbaum** [comment]
@davgar Could you test a fresh new install ?
Thx
Gilles

**Comment by davgar** [comment]
Thank you for fixing :+1:
